pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage("Checkout Java-Project") {
            steps {
                git branch: 'master', url: 'https://github.com/nag9s/simple-java-maven-app.git'
            }
        }
        stage("Clean - Java-Project") {
            steps {
                sh 'mvn clean'
            }
        }
        stage("Build - Java-Project") {
            steps {
                sh 'mvn compile'
            }
        }
        stage("Test - Java-Project") {
            steps {
                sh 'mvn test'
            }
        }
        stage("Release Package - Java-Project") {
            steps {
                sh 'mvn package'
                echo 'Java-Project is ready to release!'
            }
        }
        stage('Deploy- Java-Project') {
            steps {
                sh 'mvn install'
                echo 'Operations team can deploy Java-Project'
            }
        }
    }
}
